stages:
  - build
  - test
  - deploy

# Use Haskell Docker image.
image: haskell:8.6.5

# We want to avoid recompiling dependencies on subsequent runs of the pipeline.
# Every job that uses cabal should import this.
.cabal-cache: &cabal-cache
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ./haskellToCoqCompiler/dist-newstyle
      - ./haskellToCoqCompiler/.cabal
  # Because we cannot cache files outside of the repository, we need to
  # move the cabal directory into our repository.
  before_script:
    - mv ./haskellToCoqCompiler/.cabal /root/.cabal || true
  after_script:
    - mv /root/.cabal ./haskellToCoqCompiler/.cabal

# Compile unit tests.
build-unit-tests:
  stage: build
  <<: *cabal-cache
  script:
    - echo "Building unit tests..."
    - cd haskellToCoqCompiler
    - cabal new-update
    - cabal new-build unit-tests
    - echo "Copy unit test executable to build directory..."
    - mkdir -p ./build/bin
    - cp $(find dist-newstyle -name unit-tests -type f) ./build/bin/unit-tests
  artifacts:
    name: unit-tests
    paths:
      - ./haskellToCoqCompiler/build/bin/unit-tests

# Run unit tests.
run-unit-tests:
  stage:  test
  script:
    - echo "Running unit tests..."
    - cd haskellToCoqCompiler
    - ./build/bin/unit-tests

# Compile Haskell to Coq compiler.
build-compiler:
  stage: build
  <<: *cabal-cache
  script:
    - echo "Building compiler..."
    - cd haskellToCoqCompiler
    - cabal new-update
    - cabal new-build haskell-to-coq-compiler
    - echo "Copy executable to build directory..."
    - mkdir -p ./build/bin
    - cp $(find dist-newstyle -name haskell-to-coq-compiler -type f) ./build/bin/haskell-to-coq-compiler
  artifacts:
    name: compiler
    paths:
      - ./haskellToCoqCompiler/build/bin/haskell-to-coq-compiler

# Build Haddock documentation.
build-docs:
  stage: build
  <<: *cabal-cache
  script:
    - echo "Building Haddock documentation..."
    - cd haskellToCoqCompiler
    - cabal new-haddock --haddock-hyperlink-source
    - echo "Copy documentation to build directory..."
    - mkdir -p ./build/docs
    - cp -r $(dirname $(find dist-newstyle -name "index.html")) ./build/docs
  artifacts:
    name: docs
    paths:
      - ./haskellToCoqCompiler/build/docs

# Deploy Haddock documentation to <https://thesis.ba.just-otter.com/BRANCH/docs>.
# We are using a minimal docker image that has installed an OpenSSH client.
# There is a secret SSH_DEPLOY_KEY variable.
deploy-docs:
  stage: deploy
  image: jaromirpufler/docker-openssh-client
  script:
    - ssh-agent
