# Build PDF file for thesis.
# We are using a Docker image that has `texlive-full`, `pygments` and `pandoc`
# preinstalled. See also <https://hub.docker.com/r/aergus/latex/dockerfile>.
typeset-thesis:
  image: aergus/latex
  stage: build
  script:
    - ./LaTeX/tool/typeset.sh
  artifacts:
    name: thesis
    paths:
      - ./LaTeX/thesis.pdf

# Deploy thesis to `https://$SSH_DEPLOY_HOST/$CI_COMMIT_REF_SLUG/thesis.pdf`.
deploy-thesis:
  extends: .ssh-deploy
  stage: deploy
  dependencies:
    - typeset-thesis
  script:
    - cp ./LaTeX/thesis.pdf $DEPLOY_DIR/thesis.pdf
