# This configuration file is currently empty because the `trace` function
# is directly integrated into the compiler. The module interface still has
# to be provided since importing `Debug.Trace` would cause an error otherwise
# and without the import GHC would not be able to compile the module.
# Once support for `String`s is added, `trace` can be moved from the compiler
# to the base library entirely.

##############################################################################
# Metadata                                                                   #
##############################################################################

version = 4
module-name = 'Debug.Trace'
library-name = 'Base'
exported-types = [
  ]
exported-values = [
    # 'Debug.Trace.trace',
  ]

##############################################################################
# Tracing                                                                    #
##############################################################################

# [[functions]]
#   haskell-type    = 'forall a. Prelude.String -> a -> a'
#   haskell-name    = 'Debug.Trace.trace'
#   coq-name        = 'trace'
#   agda-name       = 'trace'
#   arity           = 2
#   effects         = []
#   needs-free-args = true

##############################################################################
# Imported from `Prelude`                                                    #
##############################################################################

# [[type-synonyms]]
#   haskell-name   = 'Prelude.String'
#   coq-name       = 'String'
#   agda-name      = 'String'
#   haskell-type   = "[Char]"
#   type-arguments = []
#
# [[types]]
#   haskell-name = 'Prelude.Char'
#   coq-name     = 'Char'
#   agda-name    = 'Char'
#   arity        = 0
#   cons-names   = []
