From Base Require Export Free.Class.
From Base Require Export Free.ForFree.
From Base Require Export Free.Induction.
From Base Require Export Free.Instance.Comb.
From Base Require Export Free.Instance.Identity.
From Base Require Export Free.Monad.
From Base Require Export Free.Strategy.
From Base Require Export Free.Tactic.ProveInd.
From Base Require Export Free.Tactic.Simplify.
