# Build PDF files for notes.
# We are using a Docker image that has `texlive-full`, `pygments` and `pandoc`
# preinstalled. See also <https://hub.docker.com/r/aergus/latex/dockerfile>.
typeset-notes:
  image: just95/pandoc-scripts
  stage: build
  script:
    - ./Markdown/tool/typeset-all.sh ./Markdown/notes --toc
  artifacts:
    name: notes
    paths:
      - ./Markdown/notes/*.pdf

# Deploy PDF files to `https://$SSH_DEPLOY_HOST/$CI_COMMIT_REF_SLUG/notes`.
deploy-notes:
  extends: .ssh-deploy
  stage: deploy
  dependencies:
    - typeset-notes
  script:
    - mkdir $DEPLOY_DIR/notes
    - cp ./Markdown/notes/*.pdf $DEPLOY_DIR/notes

# Build presentations.
typeset-presentations:
  image: just95/pandoc-scripts
  stage: build
  script:
    # - ./Markdown/tool/typeset-all.sh --beamer ./Markdown/presentation
    - ./Markdown/tool/typeset-all.sh --revealjs ./Markdown/presentation
  artifacts:
    name: presentations
    paths:
      - ./Markdown/presentation/*/bower.json
      - ./Markdown/presentation/*/*.html
      - ./Markdown/presentation/*/*.svg

# Deploy presentation to `https://$SSH_DEPLOY_HOST/$CI_COMMIT_REF_SLUG/presentations`.
deploy-presentation:
  extends: .ssh-deploy
  stage: deploy
  dependencies:
    - typeset-presentations
  script:
    - mkdir $DEPLOY_DIR/presentations
    - cd ./Markdown/presentation
    - >
      for p in $(find * -maxdepth 0 -type d); do
        mkdir $DEPLOY_DIR/presentations/$p
        cp $p/*.{json,html,svg} $DEPLOY_DIR/presentations/$p
      done

# Install bower dependencies of the deployed presentations.
bower-install-presentations:
  extends: .ssh-deploy
  stage: deploy
  when: manual
  before_script: []
  after_script: []
  script:
    - >
      ssh $SERVER '
        cd '"$TARGET_DIR"'/presentations
        for p in $(find * -maxdepth 0 -type d); do
          cd $p
          bower install
          cd ..
        done
      '
