# Build PDF files for notes.
# We are using a Docker image that has `texlive-full`, `pygments` and `pandoc`
# preinstalled. See also <https://hub.docker.com/r/aergus/latex/dockerfile>.
typeset-notes:
  image: just95/pandoc-scripts
  stage: build
  script:
    - ./Markdown/tool/typeset-all.sh ./Markdown/notes --toc
  artifacts:
    name: notes
    paths:
      - ./Markdown/notes/*.pdf

# Deploy PDF files to `https://$SSH_DEPLOY_HOST/$CI_COMMIT_REF_SLUG/notes`.
deploy-notes:
  extends: .ssh-deploy
  stage: deploy
  dependencies:
    - typeset-notes
  script:
    - mkdir $DEPLOY_DIR/notes
    - cp ./Markdown/notes/*.pdf $DEPLOY_DIR/notes
