name: CI Pipeline

# The CI pipeline runs on every push that modifies Cabal configuration, source
# or example files. If just the README or documentation changes, the pipeline
# does not have to run.
on:
  push:
    paths:
    - 'cabal.project'
    - 'free-compiler.cabal'
    - 'base/**'
    - 'example/**'
    - 'src/**'

jobs:
  #############################################################################
  # Dependencies                                                              #
  #############################################################################

  # Installs Cabal dependencies and caches the directories where cabal
  # installs the dependencies. Unfortunately, the entire code of this job
  # needs to be replicated to restore the caches in jobs that use Cabal.
  #
  # We cache `~/.cabal/packages`, `~/.cabal/store` and `dist-newstyle`
  # separately. The cache keys contain the hash of the `.cabal` and
  # `cabal.project` file as well as the hash of the `01-index.cache` file
  # from `~/.cabal/packages`.
  #
  #   * If the Cabal files in this repository change, a previous version
  #     of the cache is restored and the updated dependencies are installed.
  #     We assume this to happen only infrequently.
  #
  #   * Before the caches are populated, the latest Cabal package list is
  #     downloaded. Therefore, a change of `01-index.cache` occurs frequently.
  #     Whenever the package list is updated, a lot of dependencies have
  #     to be rebuild. If the hash of the index wouldn't be part of the
  #     cache keys, the rebuild would be triggered on every push until the
  #     Cabal files are changed. By including the indexes hash, the rebuilt
  #     dependencies are cached until the next change of the package list.
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '2.4'
    - name: Update Cabal Package List
      id: cabal-update
      run: |
        cabal new-update
        echo "::set-output name=cabal-hash::$(cat cabal.project free-compiler.cabal | sha256sum | awk '{ print $1 }')"
        echo "::set-output name=cabal-index-hash::$(cat ~/.cabal/packages/**/01-index.cache | sha256sum -b | awk '{ print $1 }')"
    - name: Cache ~/.cabal/packages
      uses: actions/cache@v1
      with:
        path: ~/.cabal/packages
        key: cabal-packages-${{ steps.cabal-update.outputs.cabal-hash }}-${{ steps.cabal-update.outputs.cabal-index-hash }}
        restore-keys: |
          cabal-packages-${{ steps.cabal-update.outputs.cabal-hash }}-
          cabal-packages-
    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
        path: ~/.cabal/store
        key: cabal-store-${{ steps.cabal-update.outputs.cabal-hash }}-${{ steps.cabal-update.outputs.cabal-index-hash }}
        restore-keys: |
          cabal-store-${{ steps.cabal-update.outputs.cabal-hash }}-
          cabal-store-
    - name: Cache dist-newstyle
      uses: actions/cache@v1
      with:
        path: dist-newstyle
        key: dist-newstyle-${{ steps.cabal-update.outputs.cabal-hash }}-${{ steps.cabal-update.outputs.cabal-index-hash }}
        restore-keys: |
          dist-newstyle-${{ steps.cabal-update.outputs.cabal-hash }}-
          dist-newstyle-
    - name: Install dependencies
      run: |
        cabal new-build freec-unit-tests --only-dependencies
        cabal new-build freec --only-dependencies

  #############################################################################
  # Unit tests                                                                #
  #############################################################################

  unit-tests:
    name: Unit tests
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '2.4'
    - name: Update Cabal Package List
      id: cabal-update
      run: |
        cabal new-update
        echo "::set-output name=cabal-hash::$(cat cabal.project free-compiler.cabal | sha256sum | awk '{ print $1 }')"
        echo "::set-output name=cabal-index-hash::$(cat ~/.cabal/packages/**/01-index.cache | sha256sum -b | awk '{ print $1 }')"
    - name: Cache ~/.cabal/packages
      uses: actions/cache@v1
      with:
        path: ~/.cabal/packages
        key: cabal-packages-${{ steps.cabal-update.outputs.cabal-hash }}-${{ steps.cabal-update.outputs.cabal-index-hash }}
        restore-keys: |
          cabal-packages-${{ steps.cabal-update.outputs.cabal-hash }}-
          cabal-packages-
    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
        path: ~/.cabal/store
        key: cabal-store-${{ steps.cabal-update.outputs.cabal-hash }}-${{ steps.cabal-update.outputs.cabal-index-hash }}
        restore-keys: |
          cabal-store-${{ steps.cabal-update.outputs.cabal-hash }}-
          cabal-store-
    - name: Cache dist-newstyle
      uses: actions/cache@v1
      with:
        path: dist-newstyle
        key: dist-newstyle-${{ steps.cabal-update.outputs.cabal-hash }}-${{ steps.cabal-update.outputs.cabal-index-hash }}
        restore-keys: |
          dist-newstyle-${{ steps.cabal-update.outputs.cabal-hash }}-
          dist-newstyle-
    - name: Install dependencies
      run: |
        cabal new-build freec-unit-tests --only-dependencies
        cabal new-build freec --only-dependencies
    - name: Build unit tests
      run: cabal new-build freec-unit-tests
    - name: Run unit tests
      run: cabal new-run freec-unit-tests

  #############################################################################
  # Executable                                                                #
  #############################################################################

  build-compiler:
    name: Build compiler
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '2.4'
    - name: Update Cabal Package List
      id: cabal-update
      run: |
        cabal new-update
        echo "::set-output name=cabal-hash::$(cat cabal.project free-compiler.cabal | sha256sum | awk '{ print $1 }')"
        echo "::set-output name=cabal-index-hash::$(cat ~/.cabal/packages/**/01-index.cache | sha256sum -b | awk '{ print $1 }')"
    - name: Cache ~/.cabal/packages
      uses: actions/cache@v1
      with:
        path: ~/.cabal/packages
        key: cabal-packages-${{ steps.cabal-update.outputs.cabal-hash }}-${{ steps.cabal-update.outputs.cabal-index-hash }}
        restore-keys: |
          cabal-packages-${{ steps.cabal-update.outputs.cabal-hash }}-
          cabal-packages-
    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
        path: ~/.cabal/store
        key: cabal-store-${{ steps.cabal-update.outputs.cabal-hash }}-${{ steps.cabal-update.outputs.cabal-index-hash }}
        restore-keys: |
          cabal-store-${{ steps.cabal-update.outputs.cabal-hash }}-
          cabal-store-
    - name: Cache dist-newstyle
      uses: actions/cache@v1
      with:
        path: dist-newstyle
        key: dist-newstyle-${{ steps.cabal-update.outputs.cabal-hash }}-${{ steps.cabal-update.outputs.cabal-index-hash }}
        restore-keys: |
          dist-newstyle-${{ steps.cabal-update.outputs.cabal-hash }}-
          dist-newstyle-
    - name: Install dependencies
      run: |
        cabal new-build freec-unit-tests --only-dependencies
        cabal new-build freec --only-dependencies
    - name: Build compiler
      run: cabal new-build freec
    - name: Copy executable to build directory
      run: |
        mkdir -p ./build/bin
        cp $(find dist-newstyle -name freec -type f) ./build/bin/freec
    - name: Upload executable
      uses: actions/upload-artifact@v1
      with:
        name: compiler
        path: ./build/bin/freec

  #############################################################################
  # Documentation                                                             #
  #############################################################################

  build-docs:
    name: Build Haddock documentation
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '2.4'
    - name: Update Cabal Package List
      id: cabal-update
      run: |
        cabal new-update
        echo "::set-output name=cabal-hash::$(cat cabal.project free-compiler.cabal | sha256sum | awk '{ print $1 }')"
        echo "::set-output name=cabal-index-hash::$(cat ~/.cabal/packages/**/01-index.cache | sha256sum -b | awk '{ print $1 }')"
    - name: Cache ~/.cabal/packages
      uses: actions/cache@v1
      with:
        path: ~/.cabal/packages
        key: cabal-packages-${{ steps.cabal-update.outputs.cabal-hash }}-${{ steps.cabal-update.outputs.cabal-index-hash }}
        restore-keys: |
          cabal-packages-${{ steps.cabal-update.outputs.cabal-hash }}-
          cabal-packages-
    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
        path: ~/.cabal/store
        key: cabal-store-${{ steps.cabal-update.outputs.cabal-hash }}-${{ steps.cabal-update.outputs.cabal-index-hash }}
        restore-keys: |
          cabal-store-${{ steps.cabal-update.outputs.cabal-hash }}-
          cabal-store-
    - name: Cache dist-newstyle
      uses: actions/cache@v1
      with:
        path: dist-newstyle
        key: dist-newstyle-${{ steps.cabal-update.outputs.cabal-hash }}-${{ steps.cabal-update.outputs.cabal-index-hash }}
        restore-keys: |
          dist-newstyle-${{ steps.cabal-update.outputs.cabal-hash }}-
          dist-newstyle-
    - name: Install dependencies
      run: |
        cabal new-build freec-unit-tests --only-dependencies
        cabal new-build freec --only-dependencies
    - name: Run Haddock
      run: ./tool/make-docs.sh
    - name: Copy documentation to build directory
      run: |
        mkdir -p ./build/docs
        cp -r $(dirname $(find dist-newstyle -name "index.html"))/. ./build/docs
    - name: Upload documentation
      uses: actions/upload-artifact@v1
      with:
        name: documentation
        path: ./build/docs

  # This job deploys the Haddock documentation generated by the `build-docs`
  # job to GitHub pages.
  #
  # This job requires a SSH deploy key for the repository. The following
  # command can be used to generate such a key.
  #
  #     ssh-keygen -t rsa -b 4096 -C "<email>" -N ""
  #
  #  - The **public key** must be given write access in the repositories deploy
  #    key menu under `Settings > Deploy Keys`.
  #
  #  - The **private key** must be added as a repository secret `DEPLOY_KEY` to
  #    the menu under `Settings > Secrets`.
  #
  # **NEVER** commit the contents of the private key!
  deploy-docs:
    name: Deploy Haddock documentation to GitHub pages
    needs: [build-docs]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install SSH Client
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Slug GitHub variables
      uses: rlespinasse/github-slug-action@master
    - name: Download documentation
      uses: actions/download-artifact@v1
      with:
        name: documentation
        path: ./build/docs
    - name: Deploy to GitHub pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        BRANCH: gh-pages
        FOLDER: build/docs
        TARGET_FOLDER: docs/${{ env.GITHUB_REF_SLUG }}

  #############################################################################
  # Base library                                                              #
  #############################################################################

  build-base-library:
    name: Build Coq base library
    runs-on: ubuntu-latest
    container: coqorg/coq:${{ matrix.coq }}
    strategy:
      matrix:
        coq: ["8.8.2", "8.11.0"]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Fix file permissions
      run: sudo chown -R coq:coq .
    - name: Setup Coq
      run: echo "::add-path::/home/coq/.opam/$COMPILER/bin"
    - name: Build Coq base library
      run: ./tool/compile-coq.sh base
    - name: Copy compiled base library to build directory
      run: |
        mkdir -p ./build/base
        cp --parents $(find base -name "*.vo" -or -name "*.glob") ./build
    - name: Upload compiled base library for Coq ${{ matrix.coq }}
      uses: actions/upload-artifact@v1
      with:
        name: coq-${{ matrix.coq }}-base-library
        path: ./build/base

  #############################################################################
  # Examples                                                                  #
  #############################################################################

  test-examples:
    name: Test examples
    needs: [build-compiler]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download compiler
      uses: actions/download-artifact@v1
      with:
        name: compiler
        path: ./
    - name: Mark compiler as executable
      run: chmod +x freec
    - name: Compile examples
      run: |
        ./freec                                          \
          --transform-pattern-matching                   \
          --dump-transformed-modules example/transformed \
          -b ./base                                      \
          -o ./example/generated                         \
          $(find ./example -name "*.hs")
    - name: Copy compiled examples to build directory
      run: |
        mkdir -p ./build/examples
        cp -r ./example/generated ./build/examples
        cp -r ./example/transformed ./build/examples
    - name: Upload compiled examples
      uses: actions/upload-artifact@v1
      with:
        name: examples
        path: ./build/examples

  test-generated-code:
    name: Test generated Coq code
    needs: [test-examples]
    runs-on: ubuntu-latest
    container: coqorg/coq:${{ matrix.coq }}
    strategy:
      matrix:
        coq: ["8.8.2", "8.11.0"]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download base library for Coq ${{ matrix.coq }}
      uses: actions/download-artifact@v1
      with:
        name: coq-${{ matrix.coq }}-base-library
        path: ./base
    - name: Download compiled examples
      uses: actions/download-artifact@v1
      with:
        name: examples
        path: ./example
    - name: Fix file permissions
      run: sudo chown -R coq:coq .
    - name: Setup Coq
      run: echo "::add-path::/home/coq/.opam/$COMPILER/bin"
    - name: Compile (generated) Coq code
      run: ./tool/compile-coq.sh ./example
